core/urls.py
from django.urls import path, include
from .views import home, logout_view, detele_task, edit_task, calendar, landing_page


app_name = 'core'

urlpatterns = [
    path('logout/', logout_view, name='logout'),
    path('', landing_page, name='landing_page'),
    path('home', home , name='home'),
    path('edit_task/<int:task_id>/', edit_task, name='edit_task'),
    path('delete_task/<int:task_id>/', detele_task, name='delete_task'),
    path('calendar/', calendar, name='calendar'),
    path('users/', include('users.urls', namespace='users')),
] 

progresio/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('users/', include('users.urls')),

] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import login_view, signup_view

app_name = 'users'

urlpatterns = [
    path('signup/', signup_view, name='signup'),
    path('login/', login_view, name='login'),
]

core/models.py
# from django.contrib.auth import get_user_model
from django.db import models
from users.models import CustomUser


# Create your models here.

class Task(models.Model):
    id = models.AutoField(primary_key=True)

    STATUS_CHOICES = [
        ('Planned', 'Planned'),
        ('Started', 'Started'),
        ('In progress', 'In Progress'),
        ('Completed', 'Completed'),
    ]
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='tasks')
    title = models.CharField(max_length=255)
    content = models.TextField(blank=True)
    start_date = models.DateField(auto_now_add=True)
    end_date = models.DateField(null=True, default=start_date)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='planned')

    def __str__(self):
        return self.title

users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import EmailValidator
from django.db import models



class CustomUser(AbstractUser):
    name = models.CharField(('name'), max_length=255)
    username = models.CharField(
        ('username'),
        unique=True,
        max_length=150,
        validators=[],
        error_messages={
            'unique': ("A user with that username already exists."),
        },
    )
    email = models.EmailField(
        ('email address'),
        unique=True,
        validators=[EmailValidator],
        error_messages={
            'unique': ("A user with that email already exists."),
        },
    )
    birthday = models.DateField(('birthday'), null=True, blank=True)

    photo = models.ImageField(upload_to='profile_photos/', default='default_photo.jpg')
    

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['name', 'email', 'birthday']

    def __str__(self):
        return self.username 

    class Meta:
        verbose_name = ('user')
        verbose_name_plural = ('users')

core/forms.py
from django import forms 
from .models import Task


class TaskCreationForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'content', 'end_date', 'status']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'end_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
        }
        labels = {
            'title': 'Title',
            'content': 'Content',
            'end_date': 'End Date',
            'status': 'Status',
        }

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import widgets
from .models import CustomUser

class CustomUserForm(UserCreationForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Password Confirmation', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    labels = {
            password1:'Password'
    }

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ['name', 'username', 'email', 'birthday']
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),
            'birthday': forms.DateInput(attrs={'class':'form-control','type': 'date'}),
        }
        labels = {
            'name': 'Name',
            'username': 'Username',
            'email': 'Email',
            'birthday': 'Birthday',
        }



class LoginForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password']
        widgets = {
            'username':forms.TextInput(attrs={'class':'form-control'}), 
            'password':forms.PasswordInput(attrs={'class': 'form-control'})
        }
        labels = {
            'username': 'Username',
            'password':'Password'
        }

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from core.forms import TaskCreationForm
from .models import Task
from django.views.decorators.cache import cache_control




#Create your views here.


def landing_page(request):
    return render(request,'core/landing_page.html')

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required(login_url='users:login')
def home(request):
    form = TaskCreationForm()
    if request.method == 'POST':
        form = TaskCreationForm(request.POST)
        form.instance.user = request.user
        if form.is_valid():
            form.save()
            return redirect('core:home')


    tasks = Task.objects.filter(user=request.user)


    context = {'form': form, 'tasks':tasks}
    return render(request, 'core/index.html', context)


@login_required(login_url='users:login')
def edit_task(request, task_id):
    task = Task.objects.get(id=task_id)
    if request.method == 'POST':
        formedit = TaskCreationForm(request.POST, instance=task)
        if formedit.is_valid():
            formedit.save()
            return redirect('core:home')
    else:
        formedit = TaskCreationForm(instance=task)
    context = {'formedit': formedit, 'task':task} 
    return render(request, 'core/edit_task.html', context)


@login_required(login_url='users:login')
def detele_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    task.delete()
    return redirect('core:home')


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required(login_url='users:login')
def calendar(request):
    tasks = Task.objects.filter(user=request.user)
    context = {'tasks':tasks} 
    return render(request, 'core/calendar.html', context)




@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def logout_view(request):
    logout(request)
    return redirect('users:login')

users/views.py
from django.shortcuts import render, redirect
from users.forms import CustomUserForm, LoginForm
from django.contrib.auth import authenticate, login
from django.views.decorators.cache import cache_control


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def signup_view(request):
    if request.method == 'POST':
        form = CustomUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:login')  
    else:
        form = CustomUserForm()
    return render(request, 'users/signup.html', {'form': form})



@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('core:home') 
    else:
        form = LoginForm()
    
    return render(request, 'users/login.html', {'form': form})

templates/core/calendar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    <title>Calendar</title>
</head>
<body>
    <nav class="navbar navbar-expand ">
        <div class="container-fluid">
                <button class="btn btn-primary slidebar-open" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling"><i class="bi bi-layout-sidebar-inset-reverse"></i>
                </button>
        </div>
    </nav>
    {% include 'core/sidebar.html' %}

    <div id='calendar' style="padding: 40px;"></div>



    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js'></script>
    <script>

        document.addEventListener('DOMContentLoaded', function() {
        var calendarUI = document.getElementById('calendar');
        var calendar = new FullCalendar.Calendar(calendarUI, {
            events: [
                {% for task in tasks %}
                {
                    'title':"{{task.title}}",
                    'start':"{{task.end_date | date:'Y-m-d'}}",
                },
                {% endfor %}
            ]
        });
        calendar.render();
        });

        document.addEventListener('DOMContentLoaded', function() {
        var dayNumbers = document.querySelectorAll('.fc-daygrid-day-number');
        if (dayNumbers.length > 0) {
            dayNumbers.forEach(function(dayNumber) {
                dayNumber.style.textDecoration = 'none';
                dayNumber.style.cursor = 'default';
                });
            }
        });


        document.addEventListener('DOMContentLoaded', function() {
        var weekdays = document.querySelectorAll('.fc-col-header-cell-cushion');
        if (weekdays.length > 0) {
            weekdays.forEach(function(weekday) {
                weekday.style.textDecoration = 'none';
                weekday.style.cursor = 'default';
                });
            }
        });



      </script>
</body>
</html>

templates/core/edit_task.html
<div class="modal-header">
    <h1 class="modal-title fs-5" id="editModalLabel{{task.id}}">Edit Task</h1>
    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
    <form action="{% url 'core:edit_task' task.id %}" method="post" >
        {% csrf_token %}
        {{ formedit.as_p }}
     <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-warning">Edit</button>
    </div>
    </form>
</div>



                               

templates/core/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    <title>Progresio | Tasks Manager app</title>
</head>
<body>
    <nav class="navbar navbar-expand ">
        <div class="container-fluid">
                    <button class="btn btn-primary slidebar-open" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling"><i class="bi bi-layout-sidebar-inset-reverse"></i></button>
                    </button>
                    <button type="button" class="btn btn-outline-light create-task" data-bs-toggle="modal" data-bs-target="#exampleModal"><i class="bi bi-plus-square"></i><span>Create Task</span></button>
                    <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h2 class="modal-title fs-5" id="exampleModalLabel">Create Task</h2>
                                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <form method="POST" class="create-form">
                                    {% csrf_token %}
                                    <div class="mb-3 form-creation-fields">
                                        {{form}}
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                        <button type="submit" class="btn btn-success">Create</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </nav>
    {% include 'core/sidebar.html' %}
    <main>
        <div class="container" style="margin-left: 20px;">
            <div class="row">  
            {% for task in tasks %}
            <div class="col-md-6 col-lg-4">
                <div class="card border-primary mb-3" style="max-width: 20rem; margin-left: 100px; margin-top: 50px;">
                    {% if task.status == 'Planned' %}
                    <span style="margin-left: 70%; margin-top: 5px; font-size: 0.8em; font-style: italic; color: #0dcaf0; font-weight: 600;">{{task.status}}</span>
                    {% elif task.status == 'Started' %}
                    <span style="margin-left: 70%; margin-top: 5px; font-size: 0.8em; font-style: italic; color: #6c757d; font-weight: 600;">{{task.status}}</span>
                    {% elif task.status == 'In progress' %}
                    <span style="margin-left: 70%; margin-top: 5px; font-size: 0.8em; font-style: italic; color: #ffc107; font-weight: 600;">{{task.status}}</span>
                    {% else %}
                    <span style="margin-left: 70%; margin-top: 5px; font-size: 0.8em; font-style: italic; color: #13653f; font-weight: 600;">{{task.status}}</span>
                    {% endif %}
                    <div class="card-body text-primary">
                        <h5 class="card-title">{{ task.title }}</h5>
                        <p class="card-text">{{ task.content|linebreaksbr|safe}}</p>
                    </div>
                    <div class="card-footer border-primary d-flex">
                        <i class="me-auto" style="margin-top: 5px;">{{ task.end_date }}</i>
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-danger ml-auto" data-bs-toggle="modal" data-bs-target="#deleteModal{{ task.id }}" style="margin-right: 5px;">
                            <i class="bi bi-trash"></i>
                        </button>
                        <!-- Modal -->
                        <div class="modal fade" id="deleteModal{{ task.id }}" tabindex="-1" aria-labelledby="deleteModalLabel{{ task.id }}" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="deleteModalLabel{{ task.id }}">Delete Task</h1>
                                        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <h4 style="padding: 20px;">Are you sure to delete "{{task.title}}" task?</h4>
                                        <form method="post" action="{% url 'core:delete_task' task.id %}">
                                            {% csrf_token %}
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                                <button type="submit" class="btn btn-danger">Delete</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <button onclick="OpenEdit('{{task.id}}')" type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#editModal{{task.id}}">
                            <i class="bi bi-pencil-square"></i>
                        </button>
                        <div class="modal fade" id="editModal{{task.id}}" tabindex="-1" aria-labelledby="editModalLabel{{task.id}}" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content" id="edit">
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                    function OpenEdit(task_id) {
                    var $ = jQuery.noConflict()
                    var url = "/edit_task/" + task_id + "/";
                    
                    $.ajax({
                        url: url,
                        method: 'GET',
                        success: function(response) {
                        $('#editModal' + task_id).find('.modal-content').html(response);
                        $('#editModal' + task_id).modal('show');
                        },
                        error: function() {
                        console.log('Error al cargar el contenido.');
                        }
                    });
                    }
            </script>
            {% endfor %}
            </div>
        </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

templates/core/sidebar.html
<div class="offcanvas offcanvas-start" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
    <div class="offcanvas-header">
        <h1>Progresio <span>✅</span></h1>
        <i class="bi bi-x-lg slidebar-closer" type="button" data-bs-dismiss="offcanvas" aria-label="Close"></i>
    </div>
    <div class="offcanvas-body">
            <div class="d-flex align-items-start">
                <div class="nav flex-column nav-pills me-3 slidebar-nav" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                    <button type="button" class="btn btn-primary slidebar-option"><i class="bi bi-list-task"></i><a href="{% url 'core:home' %}">My Tasks</a></button>
                    <button type="button" class="btn btn-primary slidebar-option"><i class="bi bi-calendar"></i><a href="{% url 'core:calendar' %}">Calendar</a></button>
                </div>
        </div>
        <div class="dropdown">
            <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{{request.user.photo.url}}"  alt="UserPhoto" width="32" height="32" class="rounded-circle me-2">
            <strong>Hi, {{request.user.name}} !</strong>
            </a>
            <ul class="dropdown-menu dropdown-menu-dark text-small">
            <li><a class="dropdown-item" href="{% url 'core:logout' %}">Log out</a></li>
            </ul>
        </div>
    </div>
</div>

templates/users/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'users/css/styles_signup.css' %}">
    <title>Log In</title>
</head>
<body>
  <main class="container">
    <div class="row">
      <div class="col-md-6 d-none d-md-block">
        <img class="signup-image " src="{% static 'users/images/login-img.jpg' %}">
      </div>
        <div class="col-md-4" id="login-box">
          <form method="POST">
            <div class="text-center">
              <h1 class="login-title">Log In</h1>
            </div>
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
              <div class="mb-3">
                <div class="text-center">
                  <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                  <p>{{field}}</p>
                </div>
              </div>
            </div>
            {% endfor %}
            <div class="text-center">
              <button type="submit" class="btn btn-primary" id="Signup">Log In</button>
              <p class="have-account">Don't you have an account? <a href="{% url 'users:signup' %}">Sign Up</a></p>
            </div>
          </form>
        </div>
      </div>
  </main>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

templates/users/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'users/css/styles_signup.css' %}">
    <title>Sign up</title>
</head>
<body>
  <main class="container">
    <div class="row">
      <div class="col-md-6 d-none d-md-block">
        <img class="signup-image " src="{% static 'users/images/signup-img.jpg' %}">
      </div>
        <div class="col-md-4">
          <form method="POST">
            <div class="text-center">
              <h1>Sign up</h1>
            </div>
            {% csrf_token %}
            {% for field in form %}
            <div class="mb-3">
              <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
              {{field}}
            </div>
              {% if field.errors %}
                <div class="text-danger">
                {% for error in field.errors %}
                <span>{{ error }}</span>
                {% endfor %}
                </div>
              {% endif %}
            {% endfor %}
            <div class="text-center">
              <button type="submit" class="btn btn-primary" id="Signup">Sign Up</button>
              <p class="have-account">Do you already have an account? <a href="{% url 'users:login' %}">Log In</a></p>
            </div>
          </form>
        </div>
      </div>
  </main>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>